export const ADD_EVENT = "ADD_EVENT";
export const TOGGLE_EVENT = "TOGGLE_EVENT";
export const RESTORE_EVENTS = "RESTORE_EVENTS";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";
